name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  matrix:
    description: matrix.
    required: false
    default: ${{ toJSON(matrix) }}
runs:
  using: 'node12'
  main: 'src/index.js'
