
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  pre:
    description: 'Job status'
    default: true
runs:
  using: "composite"
  steps:
    - uses : actions/checkout@v2
    - run: git switch -c exp origin/exp
      shell: bash
    - run : ls -al
      shell: bash
    - name: pre
      if: ${{ inputs.pre == 'true' }}
      uses: ./pre
    - name: main
      if: ${{ inputs.pre == 'false' }}
      uses: ./pre


