
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  command:
    description: 'Job status'
runs:
  using: "composite"
  steps:
    - name: retry
      uses: dmvict/wretry.action@exp
      with:
        command: ${{ inputs.command }}
        env_context: ${{ toJSON( env ) }}


