name: 'test.action'
author : dmvict
description: 'Test docker actions'
inputs:
  string:
    description: 'A string value'
    required: true
  bool-like:
    description: 'A bool like value'
    required: false
    default: true
outputs:
  result:
    description: 'Summary'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.string }}
    - ${{ inputs.bool-like }}
