
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  pre:
    description: 'Job status'
    default: 'pre'
  post:
    description: 'Job status'
    default: 'post'
  inputs:
    description: 'Job status'
    default: ${{ toJSON( inputs ) }}
runs:
  using: "composite"
  steps:
    - name: log
      run: echo "${{ toJSON(inputs) }}"
      shell: bash


