
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  pre:
    description: 'Job status'
    default: 'pre'
runs:
  using: "composite"
  steps:
    - name: pre
      if: ${{ inputs.pre == 'pre' }}
      uses: dmvict/test.action@pre_
    # - name: main
    #   if: ${{ inputs.pre != 'pre' }}
    #   uses: dmvict/test.action@main


