name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  value:
    description: 'A test value'
    required: true
  bool_default:
    description: 'A boolean with default value'
    default: 'true'
  bool:
    description: 'A boolean without default value'
runs:
  using: 'node12'
  main: 'src/index.js'
