name: 'test.action'
author : dmvict
description: 'Test action'
inputs:
  value:
    description: 'A test value'
    required: true
    default: 0
runs:
  using: 'node20'
  main: 'src/index.js'
  pre: 'src/pre.js'
  pre-if: success()
  post: 'src/post.js'
  post-if: success()
