
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  pre:
    description: 'Job status'
    default: true
runs:
  using: "composite"
  steps:
    - name: pre
      if: ${{ inputs.pre == true }}
      uses: dmvict/test.action@pre_
    - name: main
      if: ${{ inputs.pre == false }}
      uses: dmvict/test.action@main


