name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  matrix:
    description: 'Matrix context'
    default: ${{ toJSON( matrix ) }}
  matrix_os:
    description: 'Matrix OS'
    default: ${{ matrix.os }}
runs:
  using: 'node12'
  main: 'src/index.js'
