
name: 'test.action'
author : dmvict <dm.vict.kr@gmail.com>
description: 'An action for testing purpose, no real usage expected.'
inputs:
  pre:
    description: 'Job status'
    default: 'pre'
runs:
  using: "composite"
  steps:
    - name: pre
      if: ${{ inputs.pre == 'pre' }}
      run: node pre/pre.js
      shell: bash
    - name: pre
      run: node pre/main.js
      shell: bash


